databases:
  - name: categorease
    databaseName: categorease
    user: categorease_user

services:
  - type: web
    name: CategorEASE
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: categorease
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
